export enum Permission {
  SATIS_FATURASI = 'SATIS_FATURASI',
  SATIS_IADE_FATURASI = 'SATIS_IADE_FATURASI',
  ALIS_FATURASI = 'ALIS_FATURASI',
  ALIS_IADE_FATURASI = 'ALIS_IADE_FATURASI',

  ALINAN_SIPARIS = 'ALINAN_SIPARIS',
  VERILEN_SIPARIS = 'VERILEN_SIPARIS',

  ALINAN_FIYAT_TEKLIFI = 'ALINAN_FIYAT_TEKLIFI',
  VERILEN_FIYAT_TEKLIFI = 'VERILEN_FIYAT_TEKLIFI',

  DEPO_TRANSFER = 'DEPO_TRANSFER',
  SAYIM = 'SAYIM',

  STOK_KARTI_ACAR = 'STOK_KARTI_ACAR',
  CARI_KARTI_ACAR = 'CARI_KARTI_ACAR',

  STOK_RAPORLARI = 'STOK_RAPORLARI',
  CARI_RAPORLARI = 'CARI_RAPORLARI',
  FATURA_RAPORLARI = 'FATURA_RAPORLARI',
  MAGAZA_RAPORLARI = 'MAGAZA_RAPORLARI',
  OZEL_RAPORLAR = 'OZEL_RAPORLAR',

  CARI_GIRIS = 'CARI_GIRIS',
  CARI_CIKIS = 'CARI_CIKIS',

  STOK_GIRIS_BELGESI = 'STOK_GIRIS_BELGESI',
  STOK_CIKIS_BELGESI = 'STOK_CIKIS_BELGESI',

  KENDI_SUBE_CARILERINI_GORSUN = 'KENDI_SUBE_CARILERINI_GORSUN',
  BASKA_SUBEDEN_SATIS_YAPSIN = 'BASKA_SUBEDEN_SATIS_YAPSIN',

  RENK_BEDENSIZ = 'RENK_BEDENSIZ',

  ISKONTO_YAPAMAZ = 'ISKONTO_YAPAMAZ',
  SATIR_ISKONTOSU_YAPAMAZ = 'SATIR_ISKONTOSU_YAPAMAZ',

  FATURA_TARIHI_DEGISTIRIR = 'FATURA_TARIHI_DEGISTIRIR',
  KASA_DEGISTIRIR = 'KASA_DEGISTIRIR',

  PESIN_VADELI = 'PESIN_VADELI',
}
